"""
LPN for proximal operator.

---
Consider function g

g: R^{p by n} ---> R
g(X) = ||X Y^T||_{2,1}, 
where  Y \in R^{m by n} is given.

Define functional f: R^{p by n} ---> R^{p by n}
as the proximal operator of g:

f = prox_g

---
Training and testing data: 
    (X_i, f_i), 
    1) X_i's are generated by L21_data_gen in Funcs.py
    2) f_i's are f_i = prox_g(X_i), calculated by ADMM in Funcs.py.
    

The lpn_model in this code is to approximate the proximal operator.
Let H be the trained lpn_model, and for each testing point X_i,
 H(X_i) = \hat f_i.

Loss calculated between the testing f_i's and the \hat f_i's.
(default loss function is MSE: "loss_type = 2").
"""

#%% Utilities
import numpy as np
import torch
import Funcs
import matplotlib.pyplot as plt
import os
import seaborn as sns
from network import LPN_tensor
# from utils import prox, cvx, prior, gt_cvx, soft_thr, prior_eq31

sns.set()

MODEL_DIR = "experiments/models/"
os.makedirs(MODEL_DIR, exist_ok=True)

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# Set seed
np.random.seed(1)
torch.manual_seed(1)
# Set example
p = 2  # Dimension of data.

# Model parameters
beta = 10  # beta of softplus
hidden = 50  # number of hidden units
layers = 4  # number of layers


    
# Training function
def single_iteration(lpn_model, train_xx, true_f, i, bsize, optimizer, p, loss_type = 2, gamma_loss=None):
    """
    Input: 
        lpn_model --- pre-defined LPN model;
        train_xx --- data tensor for training this iteration;
        true_f --- true output tensor for training validation;
        i --- index of iteration;
        bsize --- batch size;
        optimizer --- optimizer;
        loss_type --- type of loss functions: L1, L2 (default) and L_eq31;
    """
    
    
    f_xx, xx = true_f.to(device), train_xx.to(device)
    
    f_out = lpn_model(xx)
    cvx_out = lpn_model.scalar(xx)  # cvx_out is the output psi of the LPN.

    if loss_type == 2:
        loss = (f_out - f_xx).pow(2).sum() / bsize  # MSE loss
        loss_mse = (f_out - f_out).pow(2).sum() / bsize
    elif loss_type == 1:
        loss = (f_out - f_xx).abs().sum() / bsize  # MAE loss
    # elif loss_type == 0:
    #     loss = exp_func(f_out - f_xx, gamma_loss).mean()  # proximal matching loss
    # elif loss_type == -1:   # loss induced by (3.1)

        # # R(f(y)) = y^T f(y) - 1/2 * ||f(y)||_2^2 - psi(y)
        # # Recall the R is the ||x|| - log(1/2)
        # # LHS = xx.abs() - torch.log(torch.tensor(1/2))
        # # RHS = xx * f_out - 0.5 * (f_out ** 2) - cvx_out
        # if ex == 1:   # Example 1, R is L1 norm.
        #     LHS = torch.norm(f_out, p = 1, dim = 1)
        #     RHS = torch.diag(xx @ f_out.T) - 0.5 * torch.sum(f_out ** 2, dim = 1) - cvx_out.squeeze(-1)
        # if ex == 2:   # Example 2, R is q function.
        #     LHS = 1/2 * torch.sum(f_out ** 2, dim = 1)
        #     RHS = torch.diag(xx @ f_out.T) - 0.5 * torch.sum(f_out ** 2, dim = 1) - cvx_out.squeeze(-1)
        # loss = 0.5 * (LHS - RHS).pow(2).sum()
        # loss_mse = (f_out - f_xx).pow(2).sum() / bsize  # MSE loss
    else:
        raise ValueError("loss_type must be -1, 0, 1, or 2")
        
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if i % 500 == 0:
        if loss_type == -1:
            print("l_eq31:", loss.item())
            print("mse for eq31", loss_mse.item())
        if loss_type == 2:
            print("mse:", loss.item())

    lpn_model.wclip()
    return loss, loss_mse

# Function to plot learned prox, convex function, original function
def plot_L21(plot_data, model):
    """
    input:
        plot_data for plot --- plot_amount, N, by p;
            So training with plot_amount (N ,p) data tensors, and plot 
            plot_amount * N vectors in p dim. (p == 2)
        model --- trained LPN model;
    
    return: 
    
    """

    # # lb = -4  # Lower bound of the box
    # # ub = 4   # Upper bound of the box
    # # points_per_dim = 50  # Number of points per dimension
    # xi = torch.tensor(linspace_gen(p, lb, ub, points_per_dim))
    
    xi = plot_data['xx']   # dimension amount by p by N
    true_y = plot_data['f_xx']     # dimension amount by p by N
    
    amount_dt, p, N = xi.shape
    
    if p > 2 or p < 2:
        raise ValueError("Dimension not equal to 2")
        return 0
    
    
    # run the model.
    y = model(xi)   # dimension amount by p by N
    c = model.scalar(xi)   # dimension amount by N
    
    # plot results
    vis_y = y.permute(1, 0, 2).reshape(p, amount_dt * N)
    vis_true_y = true_y.permute(1, 0, 2).reshape(p, amount_dt * N)
    
    # Scatter plot to compare the scatter plots.    

    plt.rcParams["figure.figsize"] = (8, 6)
    plt.plot(vis_y[0, :].detach().numpy(), vis_y[1, :].detach().numpy(), '*', color = 'blue', label = 'LPN')    
    plt.plot(vis_true_y[0, :].detach().numpy(), vis_true_y[1, :].detach().numpy(), 'o', markerfacecolor='none', markeredgecolor='red', markersize=8, label = 'ADMM (true)') 
    plt.title("Learned prox by LPN")
    plt.legend()
    plt.show()
    
    # print the loss on the plot case.
    loss = (y - true_y).pow(2).sum() / bsize  # MSE loss
    print("mse for the plot:", loss.detach().numpy())

#%%
# L2 loss
# Create training data. (some magic numbers for manually validation)
N = 3
gen_dt = 2000
K = int(gen_dt ** (1/(p * N)))  # Calculate grids for generating training data
m = 2
ele_lb = -1
ele_ub = 1

# Dw = torch.rand(m, N).numpy()
Dw = np.array([[1, -1, 0],
                [1, 0, -1]])

train_dt, true_f = Funcs.L21_data_gen(Dw, p, N, K, ele_lb, ele_ub)
amount_dt = train_dt.shape[0]

    
# Training
tr_dim = p * N

# Dictionary to record loss values
loss_records = {
    "mse": [],
    "l_eq31": [],
    "mse_eq31": []
}


# # Create a LPN model
lpn_model = LPN_tensor(in_dim = tr_dim, hidden=hidden, layers=layers, beta=beta).to(device)
optimizer = torch.optim.Adam(lpn_model.parameters(), lr=1e-3)
bsize = 20
# loss_type = 2 (default)
iter_thres = 1e-06

for g in optimizer.param_groups:
    g["lr"] = 1e-4
for i in range(20000):
    loss_i, _ = single_iteration(lpn_model, train_dt, true_f, i, bsize, optimizer, p)
    loss_records["mse"].append(loss_i)
    if loss_i <= iter_thres:
        break
        
    
# Save the model
torch.save(lpn_model.state_dict(), os.path.join(MODEL_DIR, "l2.pth"))

# Generate plot data:
vis_amount_data = 8

plt_data = {'xx': [],
            'f_xx': []}
#% part of training data
rand_id = torch.randint(0, amount_dt, (vis_amount_data,))
plt_data['xx'] = train_dt[rand_id]
plt_data['f_xx'] = true_f[rand_id]
#% Plot results
plot_L21(plt_data, lpn_model)


# % Creat testing data
gen_test_dt = 1000
K_test = int(gen_test_dt ** (1/(p * N)))
test_dt, test_true_f = Funcs.L21_data_gen(Dw, p, N, K_test, -1, 1)
amount_test_dt = test_dt.shape[0]
plt_test = {'xx': [],
            'f_xx': []}

vis_amount_test = 20
rand_id = torch.randint(0, amount_test_dt, (vis_amount_test,))
plt_test['xx'] = test_dt[rand_id]
plt_test['f_xx'] = test_true_f[rand_id]
# plt_test['xx'], plt_test['f_xx'] = L21_data_gen(Dw, p, N, vis_amount_data)
#% Plot results
plot_L21(plt_test, lpn_model)


# Plot convergence.
# Plot the recorded losses

plt.figure(figsize=(10, 6))
for key, values in loss_records.items():
    plt.plot(torch.tensor(values)[500:], label=key)
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Convergence of Losses")
plt.legend()
plt.grid(True)
plt.show()

